### ISSUE TITLE
How to filter out telnet negotiations from client?

### ISSUE THREAD

**Issue by geetotes** [blinkdog/telnet-stream#1]
On my telnet server, I have two event listeners:

```
telnetInput.on('sub', function(option, buffer) {
...snip...
});

socket.on('data', function(data) {
....snip...
});
```

When I receive a NAWS, the negotiation string also gets passed to my `socket`. I thought that

```
socket.pipe(telnetInput).pipe(process.stdout);
process.stdin.pipe(telnetOutput).pipe(socket);
```

Would filter the input and output to the socket in some way, but I guess not?

tldr; I'm getting an 7-bit ASCII negoation string when I do NAWS that my other socket chokes on; is this an expected behavior?

**Comment by marado** [comment]
One can't easilly replace socket calls with telnet-stream object calls, tho, since you have both input and output on the same object with a socket, while the same doesn't apply on telnet-stream objects. I mean, if you have a load of code with calls like `socket.write` and `socket.on`, you'd have now to start separating them in `telnetOutput.write` and `telnetInput.on` calls, right?

**Comment by blinkdog** [comment]
telnet-stream v1.0.3 has a new `TelnetSocket` class to handle the case described by @marado
